networks:
  frankenwp:
  dokploy-network: 
    external: true 
services:
  frankenwp:
    deploy:
      labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frankenwp.rule=Host(`frankenwp.home.lab`)"
      - "traefik.http.routers.frankenwp.entrypoints=web"
      - "traefik.http.services.frankenwp.loadbalancer.server.port=80"
    networks:
      - frankenwp
      - dokploy-network
    image: stephenmiracle/frankenwp:beta-1.0.0
    restart: always
    ports:
      - "8099:80" # HTTP
    environment:
      SERVER_NAME: frankenwp.home.lab:80
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: frankenwp
      WORDPRESS_DB_PASSWORD: frankenwp
      WORDPRESS_DB_NAME: frankenwp
      CACHE_LOC: /var/www/html/wp-content/cache
      CADDY_GLOBAL_OPTIONS: |
        email myemail@sample.com
        auto_https disable_redirects
        debug
      WORDPRESS_CONFIG_EXTRA: |
          define('WP_SITEURL', 'http://frankenwp.home.lab:8099');
          define('WP_HOME', 'http://frankenwp.home.lab:8099');
    volumes:
      - type: bind
        source: /var/lib/frankenwp/web
        target: /var/www/html
    depends_on:
      - db
    tty: true
  db:
    networks:
      - frankenwp
    image: mariadb:latest
    restart: always
    ports:
      - 3310:3306
    environment:
      MYSQL_DATABASE: frankenwp
      MYSQL_USER: frankenwp
      MYSQL_PASSWORD: frankenwp
      MYSQL_ROOT_PASSWORD: frankenwp
    volumes:
      - type: bind
        source: /var/lib/frankenwp/db
        target: /var/lib/mysql
  phpmyadmin:
    networks:
      - frankenwp
      - dokploy-network
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 6088:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: frankenwp
    depends_on:
      - db